services:
  KC-Auto-Forward-Bot:
    build: .
    environment:
      ADMINS: $ADMINS
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      COLLECTION_NAME: Telegram_files
      LOG_CHANNEL: $LOG_CHANNEL
      DATABASE_NAME: Cluster0
      DATABASE_URI: $DATABASE_URI
      TARGET_CHANNEL: $TARGET_CHANNEL
      BOT_USERNAME: $BOT_USERNAME
    resources:
      cpu: 1000m
      memory: 3Gi
